config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: "customised_registrations" }

  root 'services#index'

  resources :services, only: [:show] do
    resources :comments, only: [:create]
  end

  resources :favorites, only: [:index, :create, :destroy]

  namespace :business do
    resources :services, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

end

app/models/business.rb
module Business
  def self.table_name_prefix
    'business_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true

  has_many :services, :dependent => :destroy
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :score, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..5 }
  validates :content, presence: true

  belongs_to :user
  belongs_to :service
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  belongs_to :user
  belongs_to :service

  validates :user_id, presence: true
  validates :service_id, presence: true

end

app/models/service.rb
class Service < ActiveRecord::Base

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :category

  has_many :favorites
  has_many :users, :through => :favorites

  has_many :comments, :dependent => :destroy

  belongs_to :user

  mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base


  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :address, presence: true
  validates :phonenumber, presence: true, uniqueness: true


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :favorites
  has_many :services, :through => :favorites
  has_many :comments, :dependent => :destroy
  has_many :services_for_business, foreign_key: "user_id", class_name: "Service"


  # adds service to favorite list
  def add_as_favorite(service)
    favorites.create(service_id: service.id)
  end


  # deletes service to favorite list
  def delete_as_favorite(service)
    favorites.find_by(service_id: service.id).destroy
  end


  # returns true if user has a service as a favorite
  def has_favorite?(service)
    services.include?(service)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  before_filter :load_all_categories


  # redirect to right the url according to user role
  def after_sign_in_path_for(resource_or_scope)
    if current_user 
      if current_user.for_business?
        business_services_url
      else
        favorites_url
      end
    end
  end


  # loading all categories so they are available everywhere
  def load_all_categories
    @categories = Category.all
  end


end

app/controllers/business/services_controller.rb
class Business::ServicesController < ApplicationController


  before_action :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :require_to_be_business_provider


  def index
    @services = current_user.services_for_business
  end


  def new
    @service = Service.new
  end


  def create
    @service = current_user.services_for_business.create(service_params.merge(user: current_user))
    
    if @service.valid?
      flash[:notice] = 'Prestation crée avec succès'
      redirect_to business_services_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def show
    
  end


  def edit
    @categories = Category.all
  end


  def update
    @service.update_attributes(service_params)

    if @service.valid?
      flash[:notice] = 'Prestation modifiée avec succès'
      redirect_to business_services_path
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @service.destroy
    flash[:notice] = 'Prestation supprimée avec succès'
    redirect_to business_services_path
  end


  private

    def service_params
      params.require(:service).permit(:title, :description, :price, :category_id, :picture)
    end

    def require_to_be_business_provider
      unless current_user.for_business
        render text: "Unauthorized", status: :unauthorized
      end
    end

    def set_service
      @service = Service.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  before_action :authenticate_user!
  before_action :require_to_be_customer


  def create
    @service = Service.find(params[:service_id])
    @comment = @service.comments.create(comment_params.merge(user: current_user))

    if @comment.valid?
      flash[:notice] = "Commentaire ajouté"
    else
      flash[:alert] = @comment.errors.full_messages
    end

    redirect_to service_path(@service)
  end


  private

    def comment_params
      params.require(:comment).permit(:score, :content)
    end

    def require_to_be_customer
      if current_user && current_user.for_business
        render text: "Unauthorized", status: :unauthorized
      end
    end


end

app/controllers/customised_registrations_controller.rb
class CustomisedRegistrationsController < Devise::RegistrationsController

  def create
    super
  end

  private

    def sign_up_params
      params.require(resource_name).permit(:firstname, :lastname, :address, :phonenumber,
        :email, :password, :password_confirmation, :for_business)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  before_action :authenticate_user!
  before_action :require_to_be_customer


  def index
    @favorites = current_user.favorites
  end


  def create
    @service = Service.find(params[:service_id])
    current_user.add_as_favorite(@service)
    redirect_to service_path(@service)
  end


  def destroy
    @service = Favorite.find(params[:id]).service
    current_user.delete_as_favorite(@service)
    redirect_to service_path(@service)
  end


  private

    def require_to_be_customer
      if current_user && current_user.for_business
        render text: "Unauthorized", status: :unauthorized
      end
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  

  before_action :set_service, only: [:show]
  before_action :require_to_be_customer_or_visitor


  def index
    @services = Service.all
  end


  def show
    @comment = Comment.new
  end


  private
    
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:title, :description, :price)
    end

    def require_to_be_customer_or_visitor
      if current_user && current_user.for_business
        render text: "Unauthorized", status: :unauthorized
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business/services_helper.rb
module Business::ServicesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customised_registration_helper.rb
module CustomisedRegistrationHelper
end

app/helpers/favorite_service_helper.rb
module FavoriteServiceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/business/services/edit.html.erb
<div class="container grid-xl">
  <div class="columns">
    
    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Modifier votre prestation</h5>
    </div>

    <div class="column col-2 col-xl-2 col-lg-4 col-md-6 col-sm-8 col-xs-8">
      <% if current_user.for_business? %>
        <%= link_to  business_services_path, class: 'btn btn-primary btn-sm' do %>
            <i class="icon icon-back"></i> Précédent
        <% end %> 
      <% end %>
    </div>

    <div class="container grid-xl">
      <div class="columns">
        <div class="column col-12">
		  <%= simple_form_for @service, url: business_service_path(@service) do |f| %>
		    <%= f.input :title, label: false, placeholder: 'Title', 
		  	    input_html: { class: 'form-input' } %>
		    <br>
		    <%= f.input :description, label: false, placeholder: 'Description', 
		  	    input_html: { class: 'form-input' } %>
		    <br>
		    <%= f.input :price, label: false, placeholder: 'Price', 
		  	    input_html: { class: 'form-input' } %>
		    <br>
		    <%= f.input :category_id, collection: @categories, label: false, 
		  	    prompt: "Sélectionnez votre catégory", input_html: { class: 'form-select' } %>
		    <br>
		    <%= f.input :picture, label: false, placeholder: 'Image', 
		    	input_html: { class: 'form-input' } %>
		    <br>
		  	<%= f.submit 'Modfier', class: 'btn' %>
		  <% end %>
		</div>
	  </div>
    </div>
  </div>
</div>

app/views/business/services/index.html.erb
<div class="container grid-xl">
   <div class="columns">

    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Mes prestations</h5>
    </div>

    <div class="column col-2 col-xl-2 col-lg-4 col-md-6 col-sm-8 col-xs-8">
      <% if current_user.for_business? %>
        <%= link_to "Proposer une prestation", new_business_service_path, 
            class: 'btn btn-primary btn-sm' %>
      <% end %>
    </div>

    <% if @services && !@services.empty? %>

      <table class="table table-striped">
        <thead></thead>
        <tbody>
          <% @services.each do |service| %>
      	    <tr>
      	      <td>
                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                      <% if service.picture.present? %>
                        <%= image_tag service.picture, class: 'img-responsive' %><br>
                      <% else %>
                        <%= image_tag 'default-picture', class: 'img-responsive' %><br>
                      <% end %>
                    </div>
                  </div>
                </div>

                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                      <div class="text-bold text-uppercase">
            		        <%= service.title %>
                      </div>
                      <div class="text-break text-justify">
          		          <%= service.description %>
                      </div>
                      <div class="text-large">
          		          <%= number_to_currency(service.price, unit: '€', separator: ",", 
          			            delimiter: "", format: "%n %u") %><br>
                      </div>
                      <div class="text-italic text-lowercase">
          		          <p>#<%= service.category.name %></p>
                      </div>
                    </div>
                  </div>
                </div>
                
                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                	    <% if current_user && service.user == current_user %>
            	          <%= link_to "Voir plus", business_service_path(service), class: "btn" %>
                        <%= link_to "Modifier", edit_business_service_path(service), class: "btn" %>
                        <%= link_to "Supprimer", business_service_path(service), method: :delete, 
                            data: {confirm: 'Are you sure you want to delete this?'}, class: "btn" %>
                	    <% end %>
                    </div>
                  </div>
                </div>
    		      </td>
      	    </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="container grid-xl">
        <div class="columns">
          <div class="column col-6">
              <p>Vous n'avez pas encore proposé de prestations</p>
          </div>
        </div>
      </div>
      <%= link_to "Proposer une prestation", new_business_service_path, class: "btn" %><br>
    <% end %>
  </div>
</div>

app/views/business/services/new.html.erb
<div class="container grid-xl">
  <div class="columns">
    
    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Proposer une prestation</h5>
    </div>

    <div class="column col-2 col-xl-2 col-lg-4 col-md-6 col-sm-8 col-xs-8">
      <% if current_user.for_business? %>
        <%= link_to  business_services_path, class: 'btn btn-primary btn-sm' do %>
            <i class="icon icon-back"></i> Précédent
        <% end %> 
      <% end %>
    </div>

    <div class="container grid-xl">
      <div class="columns">
        <div class="column col-12">
		  <%= simple_form_for @service, url: business_services_path do |f| %>
		    <%= f.input :title, label: false, placeholder: 'Title', 
		  	    input_html: { class: 'form-input' } %>
		    <br>
		    <%= f.input :description, label: false, placeholder: 'Description', 
		  	    input_html: { class: 'form-input' } %>
		    <br>
		    <%= f.input :price, label: false, placeholder: 'Price', 
		  	    input_html: { class: 'form-input' } %>
		    <br>
		    <%= f.input :category_id, collection: @categories, label: false, 
		  	    prompt: "Sélectionnez votre catégory", input_html: { class: 'form-select' } %>
		    <br>
		    <%= f.input :picture, label: false, placeholder: 'Image', 
		    	input_html: { class: 'form-input' } %>
		    <br>
		  	<%= f.submit 'Créer', class: 'btn' %>
		  <% end %>
		</div>
	  </div>
    </div>
  </div>
</div>

app/views/business/services/show.html.erb
<div class="container grid-xl">
  <div class="columns">

    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Ma prestation</h5>
    </div>

    <div class="column col-2 col-xl-2 col-lg-4 col-md-6 col-sm-8 col-xs-8">
      <% if current_user.for_business? %>
        <%= link_to  business_services_path, class: 'btn btn-primary btn-sm' do %>
            <i class="icon icon-back"></i> Précédent
        <% end %>
      <% end %>
    </div>
    <div class="container grid-xl">
      <div class="columns">
        <div class="column col-12">
		  <% if @service.picture.present? %>
		    <%= image_tag @service.picture, class: 'img-responsive' %><br>
		  <% else %>
		    <%= image_tag 'default-picture', class: 'img-responsive' %><br>
		  <% end %>
		</div>
      </div>
    </div>

    <div class="container grid-xl">
      <div class="columns">
        <div class="column col-12">
          <div class="text-bold text-uppercase">
			<%= @service.title %>
		  </div>
		  <div class="text-break text-justify">
			<%= @service.description %>
		  </div>
		  <div class="text-large">
			<%= number_to_currency(@service.price, unit: '€', separator: ",",
				delimiter: "", format: "%n %u") %><br>
		  </div>
		  <div class="text-italic text-lowercase">
			<p>#<%= @service.category.name %></p><br>
		  </div>
		</div>
      </div>
    </div>

    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
	  <h5>Commentaires</h5>
	</div>

	<% @service.comments.each do |comment| %>
	  <div class="container grid-xl">
	    <div class="columns">
	      <div class="column col-12">
	        <div class="">
	  		  <%= comment.score %> / 5
	  	    </div>
	  	    <div class="text-italic">
	  		  <%= comment.content %>
	  	    </div>
	  	    <div class="text-bold">
	      	  <p>Par <%= comment.user.firstname %> <%= comment.user.lastname %></p>
	      	</div>
	  	  </div>
        </div>
      </div>
	<% end %>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="container grid-xl">
   <div class="columns">

    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Mes favoris</h5>
    </div>

    <% if @favorites && !@favorites.empty? %>

      <table class="table table-striped">
        <thead></thead>
        <tbody>
          <% @favorites.each do |favorite| %>
      	    <tr>
      	      <td>
                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                      <% if favorite.service.picture.present? %>
                        <%= image_tag favorite.service.picture, class: 'img-responsive' %><br>
                      <% else %>
                        <%= image_tag 'default-picture', class: 'img-responsive' %><br>
                      <% end %>
                    </div>
                  </div>
                </div>

                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                      <div class="text-bold text-uppercase">
            		        <%= favorite.service.title %>
                      </div>
                      <div class="text-break text-justify">
          		          <%= favorite.service.description %>
                      </div>
                      <div class="text-large">
          		          <%= number_to_currency(favorite.service.price, unit: '€', separator: ",", 
          			            delimiter: "", format: "%n %u") %><br>
                      </div>
                      <div class="text-italic text-lowercase">
          		          <p>#<%= favorite.service.category.name %><p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
    		              <%= link_to "Voir plus", favorite.service, class: "btn" %><br>
                   </div>
                  </div>
                </div>   
    		      </td>
      	    </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="container grid-xl">
        <div class="columns">
          <div class="column col-6">
    	        <p>Vous n'avez pas encore de favoris</p>
          </div>
        </div>
      </div>
      <%= link_to "Chercher des prestations", root_path, class: "btn" %><br>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KabuApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
	
  <body>
    <header class="navbar">
	    <section class="navbar-section">
	      <%= link_to "KABU APP", root_path, class: "navbar-brand mr-2" %>
	    </section>
      
		  <% if user_signed_in? %>
        <% unless current_user.for_business? %>
          <section class="navbar-section">
            <%= link_to 'Favorites', favorites_path, class: 'btn-link' %>
          </section>
        <% end %>
        <section class="navbar-section">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn-link' %>
        </section>
      <% else %>
        <section class="navbar-section">
          <%= link_to 'Sign in', new_user_session_path, class: 'btn-link' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn-link' %>
        <section>
      <% end %>
  	</header>

  	<% if notice.present? %>
	  <p class="text-success"><%= notice %></p>
    <% end %>
  	<% if alert.present? %>
      <p class="text-error"><%= alert %></p>
  	<% end %>

  	<%= yield %>

  </body>
</html>

app/views/services/index.html.erb
<div class="container grid-xl">
  <div class="columns">
    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-2">
      <h5>Les prestations</h5>
    </div>

    <table class="table table-striped">
      <thead></thead>
      <tbody>
        <% @services.each do |service| %>
      	  <tr>
      	    <td>
              <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                      <% if service.picture.present? %>
                        <%= image_tag service.picture, class: 'img-responsive' %><br>
                      <% else %>
                        <%= image_tag 'default-picture', class: 'img-responsive' %><br>
                      <% end %>
                    </div>
                  </div>
                </div>

                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
                      <div class="text-bold text-uppercase">
              		      <%= service.title %>
                      </div>
                      <div class="text-break text-justify">
            		        <%= service.description %>
                      </div>
                      <div class="text-large">
            		        <%= number_to_currency(service.price, unit: '€', separator: ",", 
            			          delimiter: "", format: "%n %u") %><br>
                      </div>
                      <div class="text-italic text-lowercase">
            		        <p>#<%= service.category.name %></p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="container grid-xl">
                  <div class="columns">
                    <div class="column col-12">
    		              <%= link_to "Voir plus", service, class: "btn" %>
                    </div>
                  </div>
                </div>
    		    </td>
      	  </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/services/show.html.erb
<div class="container grid-xl">
  <div class="columns">

    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Détail de la prestation</h5>
    </div>

    <div class="column col-2 col-xl-2 col-lg-4 col-md-6 col-sm-8 col-xs-8">
      <% if current_user %>
        <%= link_to favorites_path, class: 'btn btn-primary btn-sm' do %>
            <i class="icon icon-back"></i> Précédent
        <% end %>
      <% else %>
        <%= link_to root_path, class: 'btn btn-primary btn-sm' do %>
            <i class="icon icon-back"></i> Précédent
        <% end %>
      <% end %>
    </div>


    <div class="column col-2 col-xl-2 col-lg-4 col-md-6 col-sm-8 col-xs-8">
      <% if @service.picture.present? %>
        <%= image_tag @service.picture, class: 'img-responsive' %><br>
      <% else %>
        <%= image_tag 'default-picture', class: 'img-responsive' %><br>
      <% end %>
    </div>

    <div class="container grid-xl">
      <div class="columns">
        <div class="column col-12">
        <div class="text-bold text-uppercase">
          <%= @service.title %>
        </div>
        <div class="text-break text-justify">
          <%= @service.description %>
        </div>
        <div class="text-large">
          <%= number_to_currency(@service.price, unit: '€', separator: ",",
              delimiter: "", format: "%n %u") %>
        </div>
        <div class="text-italic text-lowercase">
          <p>#<%= @service.category.name %></p><br>
        </div>
      </div>
    </div>


    <% if current_user %>

      <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
        <h5>Mettre en favoris</h5>
      </div>

      <% if current_user.has_favorite?(@service) %>
        <%= form_for(current_user.favorites.find_by(service_id: @service.id),
          html: { method: :delete }) do |f| %>
          <%= f.submit "Supprimer des favoris", class: "btn " %>
        <% end %>
      <% else %>
        <%= form_for(current_user.favorites.build) do |f| %>
    	  <div><%= hidden_field_tag :service_id, @service.id %></div>
    	  <%= f.submit "Ajouter aux favoris", class: "btn" %>
        <% end %>
      <% end %>

      <br><br>

      <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
        <h5>Laisser un commentaire</h5>
      </div>

      <%= form_for @comment, url: service_comments_path(@service) do |f| %>
      	<div class="form-group">
          <%= f.number_field :score, label: false, placeholder: 'Note de 1 à 5', class: 'form-input' %>
          </br>
          <%= f.text_area :content, label: false, placeholder: 'Message', class: 'form-input' %>
        </div>
        <%= f.submit 'Send', class: 'btn' %>
      <% end %>
    <% end %>

    <br><br>

    <div class="column col-10 col-xl-10 col-lg-8 col-md-6 col-sm-4 col-xs-4">
      <h5>Commentaires</h5>
    </div>

    <% @service.comments.each do |comment| %>
    	<div class="container grid-xl">
        <div class="columns">
          <div class="column col-12">
            <div class="">
              <%= comment.score %> / 5
            </div>
            <div class="text-italic">
              <%= comment.content %>
            </div>
            <div class="text-bold">
              <p>Par <%= comment.user.firstname %> <%= comment.user.lastname %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>